version: "1"
services:
  employee-jdbc:
    image: create-marketing-preference
    ports:
      - "8080:8080"
    networks:
      - create-marketing-preference-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - create-marketing-preference-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  create-marketing-preference-mysql: